### ISSUE TITLE
Remote Storage Security

### ISSUE THREAD

**Issue by skibulk** [ovidiul/XCloner-Wordpress#15]
Hi I have two suggestions to improve the backup notification system.

1) An Email Address field would be useful. I am tech support for several sites so backup falls into my purview. Wordpress comment moderation on the other hand is handled by the website owners. Comments are always sent to the WP administrator email. Since XCloner also always sends to the WP admin, there is no way to separate the two.
2) I manage several sites, which I backup daily using this plugin. That means every day I get 5 backup notifications in my inbox. It would be nice to have the option to only receive a notification if an error occurred.

Lastly, I would like to know your thoughts on securing the remote storage. Basically I'm worried that, if a site is hacked, the hacker can login to wordpress, go to backups, and conveniently delete them using the little trash button that you add to each backup. I realize that delete functionality is required for cleaning up old files, and it is convenient for management purposes. But I feel like these buttons are too easy for hackers to use.

**Comment by ovidiul** [comment]
1. email notifications are always sent to the email fields you've setup on the Generate Backup screen
2. an error mail is being sent to the Wordpress site admin , so to receive only those notifications you would need to leave the email field blank from 1. setup

As for remote storage security, even if i remove that delete button and functionality, the hacker would still get access to the storage credentials and could somehow access the backups anyway, but i will take this into consideration and try to prevent the user to delete backups from remote storage through XCloner

**Comment by skibulk** [comment]
Thanks for clarifying the email stuff.

I learned that Azure offers [Shared Access Signatures](https://docs.microsoft.com/en-us/azure/storage/common/storage-dotnet-shared-access-signature-part-1), which provide limited access to Azure content. I believe they might help solve the security hole.
