### ISSUE TITLE
How to do a remote target systems restore

### ISSUE THREAD

**Issue by just-us** [ovidiul/XCloner-Wordpress#18]
Hi Liuta,

Love your plugin, it works amazingly well. I was just wondering if you could write some documentation about how to do the various types of system restore. I want to do a Remote Target Systems Restore but am not entirely sure about the first steps. Do I upload the xcloner-restore file as a plugin?

Charlie

**Comment by ovidiul** [comment]
Hi Charlie,

to restore to a remote system, please go to the XCloner Backend->Restore Menu on left side, you will see there instructions

Basically, you download the provided restore script, you upload it to the new location and after, you supply the url to it inside that input box from the restore screen and follow the onscreen instructions. This video https://www.youtube.com/watch?v=V9iWpPyG1EE does show a restore starting minute 6

Let me know if you have further questions, i have yet to find some time to write some proper docs, but i will do it at some point.

**Comment by just-us** [comment]
No worries, I kind of figured it out. I've started translating your Wordpress plugin page into UK English. I'd be more than happy to send you a translation for the plugin itself to make the English more readable to native speakers if you like?

**Comment by ovidiul** [comment]
Sure, that would be great, thanks
