### ISSUE TITLE
backup files on WEBDAV remote storage are not recognized as locally existing

### ISSUE THREAD

**Issue by poilu** [ovidiul/XCloner-Wordpress#20]
On the 'manage backups' page backup files are marked as not existing locally, although they are.
In comparison to local storage they appear in the list with the path starting '/webdav/...', not just the file name.
 
Changing line
https://github.com/ovidiul/XCloner-Wordpress/blob/2542bf39e886922dad8e94e1dfe96d0270a451aa/admin/partials/xcloner_manage_backups_page.php#L71
to `if(!$xcloner_file_system->get_storage_filesystem()->has($file_info['basename']))`
and
https://github.com/ovidiul/XCloner-Wordpress/blob/2542bf39e886922dad8e94e1dfe96d0270a451aa/admin/partials/xcloner_manage_backups_page.php#L86
to `<span class=""><?php echo $file_info['basename']?></span>`
solves the problem for me, but  I can't evaluate the impacts to other remote storage types.

**Comment by ovidiul** [comment]
I am under the impression your WebDAV Target Folder is not setup, do you have a value for that field in the Remote Storage Webdav Settings?

**Comment by poilu** [comment]
Yes, I have. The entry for the WebDAV target folder is 'wp-backups' and the upload to the corresponding directory of the Nextcloud instance I'm using works. Under the premise that I add the workaround mentioned in https://github.com/ovidiul/XCloner-Wordpress/issues/19 (to make them show up anyway) the files appear in the webdav remote storage list with the path, i.e. '/webdav/wp-backups/backup_2018-05-25_11-10-sql-part3-4ac8e.tar' while they are listed in the view of the local storage only with the file name.

**Comment by ovidiul** [comment]
Hmm, then your webdav target path should be /webdav/wp-backups/ ? the change you've done there is to list all folders recursively , i am not sure if that is the best solution. Curious to see if you get any valid upload with the path mentioned above.

**Comment by poilu** [comment]
Ah, now I see the point: I've to use 'https://nextcloud.example.com/' as WebDAV Base URL and 'remote.php/webdav/wp-backups' as WebDAV Target Folder, while 'wp-backups' is the actual directory, where the files are supposed to be stored. I thought I've to use the webdav entry point provided by nextcloud which is of the scheme https://nextcloud.example.com/remote.php/webdav/ as the base URL.
Thank's a lot!
