### ISSUE TITLE
 Header does not match it's checksum for

### ISSUE THREAD

**Issue by jayoverhol** [ovidiul/XCloner-Wordpress#22]
I created a backup on my old site, installed WP, xcloner, uploaded the xcloner_restore files and when i get to the "Restore Files Backup Available On Target Location" section and select any of the backupfiles, I get the following error...

 Header does not match it's checksum for

What am I doing wrong?

**Comment by ovidiul** [comment]
It could be the backup got corrupted during the transfer process, first check if the backup can be opened on your machine by  downloading through ftp/sftp, them try to upload it in the same way to the new location and see if you have anymore issues.
