### ISSUE TITLE
BackblazeB2\Client' not found

### ISSUE THREAD

**Issue by TobyStorm** [ovidiul/XCloner-Wordpress#27]
`Class 'BackblazeB2\Client' not found in public_html/wp-content/plugins/xcloner-backup-and-restore/includes/class-xcloner-remote-storage.php on line 551`

i've tired using the Master Application Key an bucket specific application keys noting works

The Error sometimes comes when i try to "verify"
the latest backup done is 2018-11-04

**Comment by ovidiul** [comment]
Try and reinstall XCloner with the latest dev version https://github.com/ovidiul/XCloner-Wordpress/archive/dev.zip and see if you have anymore issues, which version are you running?

**Comment by TobyStorm** [comment]
tried that. That don't fixes it.
im running a 4.9.8 wordpress 
4.0.9 xCloner

**Comment by TobyStorm** [comment]
No. still do not work. I can save all finde.
When i try to verify it, same massage. Could it be a problem with Wordfence? 
https://www.wordfence.com/

**Comment by ovidiul** [comment]
Seems there is a problem with the package posted to Wordpress repository, can you try and reinstall XCloner with the version from github (master or dev branch) https://github.com/ovidiul/XCloner-Wordpress/archive/master.zip , i will fix the package from wordpress later this week.

**Comment by TobyStorm** [comment]
Sorry that didn't work either. I just tried on a fresh instalment of wodpres 4.9.8 same error :/

**Comment by ovidiul** [comment]
Could you try the dev package instead https://github.com/ovidiul/XCloner-Wordpress/archive/dev.zip ?

commit https://github.com/ovidiul/XCloner-Wordpress/commit/7ab4058ad2b2e671c0e8a4493dc8d221152f622d

**Comment by TobyStorm** [comment]
GREAT! that works! with my "Master Application Key" and master "Account ID"

Thanks for you help!! I'll go rate the plugin MAX! 

Is there any plans for supporting multiple Application Keys? 
* https://www.backblaze.com/b2/docs/application_keys.html

**Comment by TobyStorm** [comment]
actually the dev package on the "xcloner_manage_backups_page" i can't perform any of the actions. it just update the URL with "%%SITE%%/wp-admin/admin.php?page=xcloner_manage_backups_page#%%NameOfTheBackup%% there is no

Tried on firefox an chrome

**Comment by TobyStorm** [comment]
Yeah. Thank you so much! :)

btw think you might wanna know.. running WP Fastest Cache destroys some of th features. I disabled it, but still! 
https://wordpress.org/plugins/wp-fastest-cache/

When do you plan release the update?
Thank you again!!

**Comment by ovidiul** [comment]
Can you detail the issues you are having with wp-fastest-cache plugin as i am unable to find any?

**Comment by TobyStorm** [comment]
Sorry for replying so late.. 

Sorry I've deleted wp-fastest-cache.. it never really worked.. it probably just block the js in your plugin :)

Thanks for your help again!
