### ISSUE TITLE
Differential backups, manual vs scheduled

### ISSUE THREAD

**Issue by jnbarchan** [ovidiul/XCloner-Wordpress#35]
I have a scheduled backup with **Backup name** `backup_[domain]-[time]` and setting **Backup Only Files Modified/Created After** left empty as per default.  Starting out from situation where it already has multi-part complete backup files `backup_domain-2019-02-28_15-48-part1-b20ac.tar` etc. this seems to do a Differential-only, which is good.

I then use **Generate Backups** to manually back up with *exactly* the same settings.  This time it generates a full, multi-part backup from scratch, not Differential.

I *guess* that means for *manual* I am supposed to type into the **Backup Only Files Modified/Created After** if I want it to be Differential.  But then why does *scheduled* seem to be Differential without that?  Does scheduled automatically set the date behind the scenes?  And if so, with what date --- yesterday, date of last full backup, what?  I just need to understand, perhaps that could do with documenting?

**Comment by ovidiul** [comment]
Leaving the "Backup Only Files Modified/Created " option empty either in Scheduled Backups or Generate Backup screen should give you a full backup, so please check again if that's not the case, and check the full logs as well, there is a mention there if it's partial backup only.

To create a differential backup, you need to set the time in, there is no automation there, yet...

**Comment by jnbarchan** [comment]
Well, scheduled seem to be Differential (my findings)...  Given that it's a scheduled job, how can I possibly know what date to fill in for the scheduled job when I save the job?! :)

**Comment by jnbarchan** [comment]
@ovidiul 
I do appreciate your prompt responses yesterday, but since then you have gone quiet.  I would appreciate knowing how can I specify a date for a *scheduled* backup job in order to make it Differential?  i.e. whatever date I type in might be right for the first time it runs, but what about thereafter, it needs to change all the time??

Meanwhile, in a separate issue related to the title here, I am 100% definitely finding that while *manual* backups (with no date) correctly produce the full backup each time, the *identical* settings for a *scheduled* job *always* produces a quite incorrect backup `.tar` file.  The manual full backup is 5GB split across 3 parts (2GB max per part specified) and contains all files, reliably.  A scheduled full backup produces a single file, varying anywhere between 1GB & 2GB (no pattern as to exact size within this range, varies each time).  This is clearly way less than the 5GB full, which is why I originally assumed it was Differential (I can do it straight after a full backup when *nothing* has changed anyway).  It tends to have all *files* in it from "top-level" directories, and then *all* lower level directories are simply empty of files, though they contain empty directories for each subdirectory.  It's not quite that as it varies each time, but it is thereabouts.  In all cases the log files seem to specify that everything is being backed up (and no mentions of "partial"), and there are never any error messages, but the tar file just does not contain all the files.

I am investigating further to see if I can find any pattern.  If there is any specific information you want please tell me.  Meanwhile, can you think of *anything* which could/must be involved in this weird *scheduled* behaviour to give us a clue as to how to track it down?

**Comment by ovidiul** [comment]
The differential date doesn't change automatically, you would need to manually change it.

As for the variable size, that usually means your backups are corrupt and are probably being stopped from finishing by the server, most probably a timeout. In that case, i suggest setting up a CLI based worpress cron job.

**Comment by jnbarchan** [comment]
Thank you very much.

I had assumed the purpose of the scheduled differential backup was to be able to automatically generate a differential backup *each time* from the *last time* it had been run, on a "rolling" basis, but obviously not.

Having spent two days playing with it, I too had come to your conclusion that somewhere behind the scenes the (shared) hosted server must be terminating the scheduled backup process.  I cannot access any logs/error messages etc. which show this, and I am at a loss to understand why this would apply to *scheduled* one but not *manual* ones which seem to take about the same time (the only timeout I can see is `PHP max_execution_time : 50000`, I think the manual backup takes longer than that and still works anyway, and I didn't have any luck trying to alter that in `.htaccess` if you're supposed to be able to do so), but there you are.

I tried playing around with cron, but it all got a bit beyond me.  My provider (1&1 IONOS) does have a "cron" panel, but it *only* allows you to specify a single *URL* for the job, no commands/command-line stuff.  So I don't know how to do it.  Your software does warn me that "I ought to set `WP_DISABLE_CRON` to true", but reading the article I can't see how that would help as that only alters when the job-time-checks get executed, which does not seem related to my issue.

If you have any further suggestions please let me know; thanks very much for your time.

**Comment by ovidiul** [comment]
The manual backup option uses ajax javascript to create a backup in smaller chuncks request to prevent timeouts, while schedule ones are executed in one full batch. 

Since your hosting provider only allows web based cron execution, i would suggest to try and create smaller backups by excluding the larger resources or to simply create a full backup manually and then schedule differential backups with a date set of the full backup, so it will backup only files changed after that date.

**Comment by jnbarchan** [comment]
Ah, now that you say about the ajax-split for manual backups, I now know what the difference is which makes the scheduled fail!  At least I understand, thank you for your help.

**Comment by martin-braun** [comment]
I have the same issue, my scheduled backups are too small. @jnbarchan, thank you for making this issue, @ovidiul, thank you for making this awesome tool and thank you for clarifying. 

So what is the fix about that? Increasing `max_execution_time`? This is really unfulfilling in a way. Isn't there a better solution? Should the issue here really be closed? I really want full scheduled backups.

**Comment by ovidiul** [comment]
@martin-braun it would be best to open a new issue and detail the problem you are having, if possible, please post details on your current scheduled cron config as well.

**Comment by martin-braun** [comment]
@ovidiul Alright, I did so on #179. Thanks.
