### ISSUE TITLE
Xcloner-Wordpress allows upgrade when PHP version is not appropriate

### ISSUE THREAD

**Issue by jsavage** [ovidiul/XCloner-Wordpress#9]
Hi,
I have just encountered an issue where I upgraded the xcloner plugin only to find that the upgraded plugin is not compatible with the version of PHP on my server.  I also notice that when I go to Add Plugin feature in Wordpress that it states that Xcloner is Compatible with your version of WordPress.
Unfortunately until I can upgrade my hosting account I am stuck with php 5.2 and at that point I will need Xcloner working.  
Please could someone advise how I can install a version of Xcloner that works with PHP 5.2.

**Comment by ovidiul** [comment]
HI there, you can use the 3.1.5 version which is compatible with your version of php, you can download it from here https://downloads.wordpress.org/plugin/xcloner-backup-and-restore.3.1.5.zip
